
[window]
startup_mode = "Maximized"

[mouse]
hide_when_typing = true

[terminal.shell]
program = "/bin/bash"
args = [
	"-l",
	"-c",
	"tmux attach || tmux",
]

[font]
size = 20.0

[general]
import = [
    "~/.config/alacritty/rose-pine-moon.toml"
]

[terminal]
